### ISSUE TITLE
Hardware requirement to build a FAISS index from the dense embedding?

### ISSUE THREAD

**Issue by evelynkyl** [AkariAsai/CORA#1]
Hi,

First of all, thank you for sharing the great work! 

I'm trying to replicate the implementation on another platform (ParlAI) and I have been building a FAISS index from the multilingual embeddings provided in this repo on a GPU with 50 GB vram. I used the FAISS compression techniques so it's supposed to build an index much faster. However, the program has been running for ~48 hours now and not stopping. I've also tried building it without the compression techniques but that took days and the cost became to high for me.

I'm wondering what is the hardware requirement to build such an index and how long would it take? Also would it be possible to share the index file you built?

Thank you so much!

**Comment by AkariAsai** [comment]
Thank you for your interest! During our experiment, we used 8 GPUs * 32 GRAM and 200 GB CPU RAM and it took around 10 hours as far as I remember. If you are trying to generate embeddings using a single GPU, it can take 50 hours, unfortunately... 
This issue was also mentioned by the DPR authors:
[DPR/issues/3](https://github.com/facebookresearch/DPR/issues/3#issuecomment-629450049)
Yet, I haven't tried the compression version so I'm not sure if there are any other issues... 

You can download our indices following our script: [quick_start_xorqa.sh](https://github.com/AkariAsai/CORA/blob/main/quick_start_xorqa.sh). 

This discussion between me and a DPR author might help:
[DPR/issues/6](https://github.com/facebookresearch/DPR/issues/6)

**Comment by evelynkyl** [comment]
Thank you for your reply! I have downloaded the dense embeddings provided by you, but the problem I'm having is the FAISS index building where it runs out of memory because of the lack of enough vram in my GPU.

I'll try to use both the compression techniques mentioned by the DPR author and build smaller indices, then combining them all together.

Thanks again for your help!
